### ISSUE TITLE
On demand video

### ISSUE THREAD

**Issue by ofadam** [MakuZo/kamerowanie#2]
Is there a way to adjust this tool to only pull the originating video stream on demand (to lessen bandwidth needs)?

**Comment by piotr-kopacki** [comment]
It's possible and there are multiple ways to handle that
Easiest way would be to run/kill the script whether the feed is needed but this would result in a long start up time.
I think the most efficient way would be to fire SIGSTOP/SIGCONT signal on ffmpeg process though this would require some modifications on this script and tests to see if ffmpeg would resume correctly.
